### PR TITLE
FIX: Invalid topic used to publish request for outstanding OTA jobs

### LINKED ISSUE #480: [BUG] Invalid topic used to publish request for outstanding OTA jobs
**Describe the bug**
This looks like a regression in commit e43672a0, the thing name is not added to the topic parts in function requestJob_Mqtt() in source/ota_mqtt.c.

**Host**
ESP32 with FreeRTOS/ESP-IDF

**To Reproduce**
Initialize the OTA agent, causing it to request outstanding OTA jobs, which will fail with AWS dropping the connection.

### PR DESCRIPTION
**Pull request by paulbartell**
FIX: Invalid topic used to publish request for outstanding OTA jobs

Description
-----------
From the original poster @imoir:

> This looks like a regression in commit https://github.com/aws/ota-for-aws-iot-embedded-sdk/commit/e43672a0881d6aad65df3a61ece5a4e019c3559f, the thing name is not added to the topic parts in function requestJob_Mqtt() in source/ota_mqtt.c.

fix #480 

Checklist:
----------

- [X] I have tested my changes. No regression in existing tests.
- [X] My code is formatted using Uncrustify.
- [X] I have read and applied the rules stated in CONTRIBUTING.md. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by archigup — DISMISSED** [review]

**Comment by kstribrnAmzn** [comment]
Can we expand the unit tests to catch this issue in the future?

File: test/unit-test/ota_utest.c [hunk 1]
```diff
@@ -467,6 +467,31 @@ static OtaMqttStatus_t stubMqttPublish( const char * const unused_1,
...
+{
+    ( void ) unused_1;
+    ( void ) unused_2;
+    ( void ) unused_3;
+
+    /* Maximum topic size is 128 characters for IoT Core */
+    TEST_ASSERT_LESS_OR_EQUAL( 128U, topicLength );
+    TEST_ASSERT_GREATER_THAN( 1U, topicLength );
+
+    char expected[ 129 ] = { 0 };
```
Comment (kstribrnAmzn) [inline test/unit-test/ota_utest.c:484]: Note: this could be even tighter. Left a bit relaxed incase we change the default topic name

**Comment by kstribrnAmzn** [comment]
Test output with the change....
```
ctest
Test project /home/ubuntu/ota-for-aws-iot-embedded-sdk/build
    Start 1: ota_utest
1/4 Test #1: ota_utest ........................   Passed    0.02 sec
    Start 2: ota_base64_utest
2/4 Test #2: ota_base64_utest .................   Passed    0.00 sec
    Start 3: ota_cbor_utest
3/4 Test #3: ota_cbor_utest ...................   Passed    0.00 sec
    Start 4: ota_os_posix_utest
4/4 Test #4: ota_os_posix_utest ...............   Passed    5.01 sec

100% tests passed, 0 tests failed out of 4
```

Test failure if I rollback the source change....
```
ctest
Test project /home/ubuntu/ota-for-aws-iot-embedded-sdk/build
    Start 1: ota_utest
1/4 Test #1: ota_utest ........................***Failed    0.02 sec
    Start 2: ota_base64_utest
2/4 Test #2: ota_base64_utest .................   Passed    0.00 sec
    Start 3: ota_cbor_utest
3/4 Test #3: ota_cbor_utest ...................   Passed    0.00 sec
    Start 4: ota_os_posix_utest
4/4 Test #4: ota_os_posix_utest ...............   Passed    5.01 sec

75% tests passed, 1 tests failed out of 4

Total Test time (real) =   5.03 sec

The following tests FAILED:
	  1 - ota_utest (Failed)
```

The logs show the failed expectation...`/home/ubuntu/ota-for-aws-iot-embedded-sdk/test/unit-test/ota_utest.c:490:test_OTA_MQTT_PublishesToCorrectTopic:FAIL: Expected '$aws/things/ota_utest/jobs/$next/get' Was '$aws/things/'`

**Review by AniruddhaKanhere — DISMISSED** [review]

**Review by AniruddhaKanhere — APPROVED** [review]

**Review by kstribrnAmzn — APPROVED** [review]
